name: Build Step

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.20.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run CI
        run: npm ci
      - name: Run Build
        run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        uses: actions/checkout@v3
      - name: Dummy test 
        run: echo 'running tests'

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: ['build', 'test']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}
      - name: Build image and push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            salsabiilashifa11/gitops-demo:${{ github.sha }}
            ghcr.io/salsabiilashifa11/gitops-demo:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: salsabiilashifa11/gitops-demo-config
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
      - name: Setup git config 
        run: |
          git config --global user.email "salsabiilashifa11@gmail.com"
          git config --global user.name "salsabiilashifa11"
          echo ${{ github.sha }}
          sed -i "s#${{ github.actor }}.*#${{ github.actor }}/gitops-demo:${{ github.sha }}#g" deployment.yaml
          git add -A 
          git commit -am "update image to: ${{ github.sha }}"
      - name: Echo github 
        run: echo ${{ github }}
      - name: Push changes 
        run: git push origin main
